name: all_gallery_images
description: Flutter plugin use to fetch all the images from the storage in Android and iOS .
version: 0.1.0
homepage: https://devblog.link
repository: https://github.com/raju8000/all_gallery_images.git

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.plugin.allgalleryimages
        pluginClass: AllGalleryImagesPlugin
      ios:
        pluginClass: AllGalleryImagesPlugin
